version:  "3.8"

#services
services:
  backend:
    container_name: java_app
    image: java_app
    restart: always
    build: ./
    ports:
      - "4444:4444"  
    networks:
      - java-network
  
#networks
networks:
  java-network:
    name: java-network
    driver: bridge

  
