version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache_tomcat_deployment
    container_name: tomcat
    ports:
      - "8080:8080"
    networks:
      - tomcat-network

networks:
  tomcat-network:
    driver: bridge
