version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 9
    ports:
      - "80:80"  
    networks:
      - web_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
networks:
  web_network:
    driver: overlay  
